services:
  app:
    image: rggouale/faithtools:latest
    ports:
      - 3000:3000
    env_file:
      - .env.local
    networks:
      - faith-tools
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=faithtools
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - faith-tools

  authdb:
    image: postgres:latest
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - authdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5434:5432
    expose:
      - 5434
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - faith-tools

  stackauth:
    image: stackauth/server:latest
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@authdb:5432/faithtoolsauth
    ports:
      - 8101:8101
      - 8102:8102
    restart: always
    networks:
      - faith-tools
    platform: linux/amd64
    volumes:
      - stackauth:/app

    depends_on:
      authdb:
        condition: service_healthy

volumes:
  db-data:
  stackauth:
  authdb-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  faith-tools:
    driver: bridge
